# generates the parser with 'tree-sitter generate' if the parser is out of date
name: Generate Parser

on:
  push:
    branches:
      - main
jobs:
  generate:
    name: Generate Parser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - name: Generate parser files
        run: tree-sitter generate

      - name: Commit generated parser files
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add src
          git commit -m "Generate parser" || true
          git push
